"""The layout: a topology snapshot in, object patches for a `web` cell out.

THIS FILE IS THE SOURCE. `config.json` carries a copy of it in `script_inline`,
generated by `scripts/canvy_sync.py` and pinned by a test in
`crates/meclaw-cells/tests/canvy2_pipeline.rs`. Edit here, then run:

    python3 scripts/canvy_sync.py

Why the copy exists at all: a `code` cell's `script_path` is handed to the
interpreter verbatim with no working directory of its own (the factory ignores
`cell_dir` -- `code` is stateless), so a relative path would resolve against the
daemon's cwd, and an absolute path baked into a template is the exported-tree
defect class of GH #20. So the runtime form is `script_inline`, and this file is
what a person reads, greps, diffs and runs:

    python3 templates/canvy/layout/layout.py < some-web-answer.json

The same generator substitutes `client.js` and `client.css` into the two
constants below, which is why they read as placeholders here and as the real
files in `config.json`.

# What this cell is

It is the whole picture, and it draws it as OBJECTS rather than as HTML. The
`web` cell holds an object tree, a component library and a page; this cell says
what belongs in that tree. A new kind of thing on the canvas is therefore a
template edit -- one more component and one more patch -- and never a release.

It is NOT the owner of the topology. That comes from `/colony/graph`, by message,
through this hive's own `./probe` lane, on a timer -- never read out of a
database, and never fetched inside a browser's request (a `/colony` reply arrives
on a fresh envelope with no context, so it could not be correlated back to
whoever asked).

It is also NOT the owner of a position. A cell the display already knows keeps
the `x`/`y` it has, because a person may have dragged it there and a drag is a
LOCAL write inside the `web` cell that nothing here ever hears about. Only a
cell the display has never seen is given a computed spot. That is the whole of
"positions only for objects the web DB does not know yet".

# The three passes, and why there are three

Pass 1 (the probe's snapshot): emit ONE `query` over the page. The graph rides
along in `hop.canvy_graph`, which the hive's `./layout -> ./web` edge promotes
into `context` -- `hop` survives exactly one edge, and pass 2 is two edges away
(layout -> web -> layout). Carrying it in `hop` alone would lose it silently, the
same trap the 1.x render cell fell into with a drop's coordinates.

Pass 2 (the display answered): compute the layout against the objects that exist
and emit one bundle of `object.*` calls. A refusal here is not a failure but the
BOOTSTRAP case: a `web` cell whose page has never been set answers `query` with
`invalid_input`, which is the only honest signal that this display is empty, and
the same bundle then defines the components, creates the root and sets the page.

Pass 3 (the display acknowledged the patch): emit NOTHING. This pass is the whole
reason the cell needs a discriminator at all. Before the equivalent check existed
in 1.x, every store acknowledgement fell through to "ask again" -- one tick became
two, two became four, and the routing loop wedged on a full mailbox inside twenty
seconds (GH #161). A cell that cannot recognise the reply to its own write has no
way to stop.
"""
import json
import sys
import uuid

# Substituted by `scripts/canvy_sync.py` from `canvy.js` and `canvy.css`. The
# layout writes them into the root object's two raw props exactly once, on the
# bootstrap pass: they are the largest thing this cell ever says and they do not
# change between ticks.
CLIENT_JS = "@@CANVY_JS@@"
CLIENT_CSS = "@@CANVY_CSS@@"

# The layout constants. The client reads them back off the markup rather than
# keeping a second copy, so a frame computed during a drag is the frame the next
# patch brings back.
NODE_W, NODE_H = 150, 38
# Between two columns of the flow, and between two boxes stacked in one column.
# The horizontal gap is the larger one on purpose: the flow reads left to right,
# and the eye needs the steps along that axis to be the obvious ones.
GAP_X, GAP_Y = 90, 34
# The air between two wrapped rows of columns -- bigger than the gap inside a
# column, so a wrap reads as "the flow continues below" and not as a new branch.
ROW_GAP = 70
# How wide a block may get relative to its height before its columns wrap.
TARGET_RATIO = 2.0
# ...and how wide it has to be before wrapping is considered at all. A four-cell
# chain is a 918-pixel stripe and perfectly readable as one; breaking it into a
# tower to satisfy a ratio makes the flow harder to follow, not easier. Wrapping
# is a remedy for blocks that outgrow a screen, not a rule about shape.
WRAP_MIN_W = 1100
PAD_TOP, PAD_SIDE, PAD_BOT = 30, 24, 24
# How far INSIDE its parent a hive's frame sits. Constant, not a function of
# depth: an ancestor is bigger than its child by this much at every level, which
# is what makes nesting readable without measuring, and what lets the client
# recompute a frame during a drag with the same arithmetic this cell used.
NEST = 18
# How many depths the stylesheet has a tint for. Deeper hives keep the last one.
# Ten, because a real colony gets deep: `/org/<org>/member/<who>/assistants/<name>/
# talky/keeper` is already eight, and two hives at different depths sharing a colour
# is exactly the thing the tint exists to prevent.
HIVE_DEPTH_TINTS = 10

# Fill and stroke per cell type.
TYPE_COLOR = {
    "llm": ("#d6e4ff", "#4a6fa5"),
    "code": ("#e8e8e8", "#8a8a8a"),
    "file": ("#e8e8e8", "#8a8a8a"),
    "edit": ("#e8e8e8", "#8a8a8a"),
    "store": ("#ffe6cc", "#d79b00"),
    "proxy": ("#d5e8d4", "#82b366"),
    "timer": ("#fff2cc", "#d6b656"),
    "web": ("#dae8fc", "#6c8ebf"),
    "web_fetch": ("#f8cecc", "#b85450"),
    "web_search": ("#f8cecc", "#b85450"),
    "bash": ("#e1d5e7", "#9673a6"),
    "harness": ("#e1d5e7", "#9673a6"),
    "mcp": ("#e1d5e7", "#9673a6"),
    "vault": ("#f5f5f5", "#666666"),
    "subcolony": ("#dae8fc", "#6c8ebf"),
}
DEFAULT_COLOR = ("#ffffff", "#999999")

# The object ids, by class. Prefixed rather than bare, because a cell path and a
# hive path can be the same string in two different roles -- `/a/b` is a cell in
# one colony and a hive in another -- and one id space that could not tell them
# apart would silently patch the wrong object.
ROOT_ID = "canvy"
NODE_PREFIX = "n/"
HIVE_PREFIX = "h/"
EDGE_PREFIX = "e/"

# ---------------------------------------------------------------------------
# The component library. Data, not code: a `web` cell's `component.define` takes
# a template written in the closed four-form language ({{prop}}, {{&prop}},
# {{children}}, {{#if prop}}...{{/if}}) and nothing else, and it parses it at
# DEFINITION time -- so a mistake here is answered to this cell, not rendered as
# a blank area on somebody's screen.
#
# `{{&client_css}}` and `{{&client_js}}` are raw on purpose, and the schema types
# them `"html"`, which is what makes them raw: a `{{&prop}}` whose schema does not
# say `"html"` is escaped instead, and a stylesheet rendered escaped is a page
# with no style at all. Everything else is escaped by default -- a cell path is
# database content and a name carrying `<script>` must not be able to close a tag.

SHELL_TEMPLATE = (
    '<div class="canvy" id="canvy" phx-hook="Canvy" data-title="{{title}}"'
    ' data-nw="{{nw}}" data-nh="{{nh}}" data-pad-side="{{pad_side}}"'
    ' data-pad-top="{{pad_top}}" data-pad-bot="{{pad_bot}}" data-nest="{{nest}}">'
    "<style>{{&client_css}}</style>"
    "<script>{{&client_js}}</script>"
    '<svg class="stage" xmlns="http://www.w3.org/2000/svg" viewBox="{{viewbox}}"'
    ' preserveAspectRatio="xMidYMid meet">'
    # The arrowheads. The stylesheet asks for `url(#ar)`; in 1.x nothing ever
    # defined it, so every edge in every picture was an undirected line -- 123 of
    # them on a real colony, with no way to tell which way anything flowed.
    # `orient="auto-start-reverse"` keeps the head pointing along the path however
    # the router turned it.
    "<defs>"
    '<marker id="ar" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6.5"'
    ' markerHeight="6.5" orient="auto-start-reverse">'
    '<path d="M0,0 L10,5 L0,10 z" fill="var(--edge)"/></marker>'
    '<marker id="arh" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6.5"'
    ' markerHeight="6.5" orient="auto-start-reverse">'
    '<path d="M0,0 L10,5 L0,10 z" fill="var(--edge-hot)"/></marker>'
    "</defs>"
    # The camera transform lives on this group and is written by the client alone.
    # It starts at identity: the `viewBox` above already frames the whole drawing,
    # so a fresh load is legible before any script runs.
    '<g class="viewport">{{children}}</g>'
    "</svg>"
    # Somewhere to say what was clicked. Without it the whole selection idea is
    # invisible and an edge's condition stays a string in an attribute nobody can
    # read. The panel is filled by the client -- this cell renders the frame, not
    # the answer, because what is selected is a client-side fact.
    '<aside id="detail" class="detail"><p class="empty">Click a cell or an edge.</p></aside>'
    '<div class="legend">{{cells}} cells, {{hives}} hives, {{edges}} edges</div>'
    "</div>"
)

HIVE_TEMPLATE = (
    # `depth-N` is what the stylesheet tints. Clamped, because a tree deeper than
    # the palette should keep the deepest colour rather than fall back to none --
    # a hive with no tint would read as "not a hive".
    '<g class="hive depth-{{depth}}" data-hive="{{path}}">'
    '<rect x="{{x}}" y="{{y}}" width="{{w}}" height="{{h}}" rx="10"/>'
    '<text x="{{tx}}" y="{{ty}}">{{name}}</text>'
    "</g>"
)

EDGE_TEMPLATE = (
    # Two paths per edge and both matter. The thin one is the line; the fat
    # transparent one is what a mouse can hit -- an edge is 1.4 px wide, and
    # "click an edge to read its condition" is not a feature you can offer on
    # 1.4 px.
    #
    # `cond` is a CLASS and not only a data attribute: the stylesheet dashes a
    # conditional edge, and half of a real colony's edges carry a condition. A
    # picture that draws them like the rest hides exactly what an operator came to
    # look for. The condition text and the modifier ride along so that clicking
    # the edge can show them in full without another round trip.
    '<g class="edge-g">'
    '<path class="edge{{#if cond}} cond{{/if}}" data-edge="{{eid}}"'
    ' data-from="{{from}}" data-to="{{to}}" data-lane="{{lane}}"'
    ' data-cond="{{cond}}" data-mod="{{mod}}"/>'
    '<path class="edge-hit" data-edge="{{eid}}"/>'
    "</g>"
)

NODE_TEMPLATE = (
    # `data-node` is the colony PATH -- what an edge names, and what the client's
    # frame arithmetic splits on. `data-oid` is the OBJECT id, which is what a
    # drag patches. Keeping them apart is what lets a hive frame and a cell of the
    # same path both exist as objects.
    #
    # `unwired` says the cell takes part in no edge at all. In this substrate that
    # is almost always a DISCONNECTED cell -- `remove_nodes` drops every edge and
    # keeps the node (no-delete), so a rewiring leaves its predecessor standing in
    # the picture looking exactly like a live one. It is a heuristic and not an
    # answer (the graph endpoint does not report activity), which is why it dims
    # rather than hides: a cell instantiated a second ago and not yet wired looks
    # the same, and that is a state worth seeing too.
    '<g class="node{{#if unwired}} unwired{{/if}}" data-node="{{path}}"'
    ' data-oid="{{oid}}" transform="translate({{x}},{{y}})">'
    '<rect width="{{w}}" height="{{h}}" rx="6" fill="{{fill}}" stroke="{{stroke}}"/>'
    '<text class="nm" x="8" y="16">{{name}}</text>'
    '<text class="ty" x="8" y="30">{{type}}</text>'
    "</g>"
)


def components():
    """The four component definitions, in the order they are defined."""
    return [
        {
            "name": "canvy-shell",
            "template": SHELL_TEMPLATE,
            "prop_schema": {
                "title": "text",
                "viewbox": "text",
                "cells": "int",
                "hives": "int",
                "edges": "int",
                "nw": "int",
                "nh": "int",
                "pad_side": "int",
                "pad_top": "int",
                "pad_bot": "int",
                "nest": "int",
                "client_css": "html",
                "client_js": "html",
            },
            "editable": [],
            "layer": "content",
        },
        {
            "name": "canvy-hive",
            "template": HIVE_TEMPLATE,
            "prop_schema": {
                "path": "text",
                "name": "text",
                "depth": "int",
                "x": "int",
                "y": "int",
                "w": "int",
                "h": "int",
                "tx": "int",
                "ty": "int",
            },
            # A frame is DERIVED from the cells it holds, so there is nothing for a
            # browser to write here: dragging a hive moves its members, and the
            # frame follows from where they end up.
            "editable": [],
            "layer": "content",
        },
        {
            "name": "canvy-edge",
            "template": EDGE_TEMPLATE,
            "prop_schema": {
                "eid": "text",
                "from": "text",
                "to": "text",
                "lane": "int",
                "cond": "text",
                "mod": "text",
            },
            "editable": [],
            "layer": "content",
        },
        {
            "name": "canvy-node",
            "template": NODE_TEMPLATE,
            "prop_schema": {
                "path": "text",
                "oid": "text",
                "name": "text",
                "type": "text",
                "x": "int",
                "y": "int",
                "w": "int",
                "h": "int",
                "fill": "text",
                "stroke": "text",
                "unwired": "text",
            },
            # The one declaration that makes a drag possible at all. The `web`
            # cell checks it against the COMPONENT, never against the message: a
            # browser says what it wants changed, and the component says what may
            # be.
            "editable": ["x", "y"],
            "layer": "content",
        },
    ]


# ---------------------------------------------------------------------------
# The tree the colony graph describes


def hive_of(path):
    """The parent path of a cell, without its leading slash. "" at the root."""
    p = path.strip("/")
    return p.rsplit("/", 1)[0] if "/" in p else ""


def element_of(path, hive):
    """Which element of `hive` a cell belongs to: itself, or the child hive.

    A hive is laid out over ITS OWN elements -- the cells that live directly in it
    and the child hives, each as one block. So an edge to a cell three levels
    down is, from here, an edge to the child hive that contains it. Projecting
    edges this way is what makes the flow visible at every level instead of only
    at the leaves.
    """
    if hive:
        if not path.startswith(hive + "/"):
            return None
        rest = path[len(hive) + 1:]
    else:
        rest = path
    head = rest.split("/", 1)[0]
    return (hive + "/" + head) if hive else head


def back_edges(ids, pairs):
    """The edges that point backwards in a depth-first walk.

    A colony graph is full of cycles by design -- every request/reply pair is one,
    and a picture that tries to rank a cycle either spins or produces nonsense.
    So the walk names the edges that close a loop, ranking ignores them, and they
    are still DRAWN: they are precisely the "and back up again" lanes, and they
    read correctly once the forward flow has decided the columns.
    """
    out = {}
    for a, b in pairs:
        out.setdefault(a, []).append(b)
    state = {}
    back = set()
    for root in ids:
        if state.get(root):
            continue
        state[root] = 1
        stack = [(root, sorted(set(out.get(root, [])), reverse=True))]
        while stack:
            node, rest = stack[-1]
            if not rest:
                state[node] = 2
                stack.pop()
                continue
            nxt = rest.pop()
            if state.get(nxt) == 1:
                back.add((node, nxt))
            elif not state.get(nxt):
                state[nxt] = 1
                stack.append((nxt, sorted(set(out.get(nxt, [])), reverse=True)))
    return back


def columns_of(ids, pairs):
    """A column per element: one to the RIGHT of everything that feeds it.

    Left to right is the direction a turn travels, so it is the direction the
    picture puts it in. Longest path from the sources, on the graph with its back
    edges removed -- which terminates, because what is left is a DAG.
    """
    back = back_edges(ids, pairs)
    fwd = [(a, b) for (a, b) in pairs if a != b and (a, b) not in back]
    incoming = {i: [] for i in ids}
    for a, b in fwd:
        incoming[b].append(a)
    col = {i: 0 for i in ids}
    for _ in range(len(ids) + 1):
        changed = False
        for i in ids:
            want = max([col[s] + 1 for s in incoming[i]], default=0)
            if want != col[i]:
                col[i] = want
                changed = True
        if not changed:
            break
    return col, fwd


def spine_of(ids, fwd, col):
    """The elements on a LONGEST chain through the flow.

    They are drawn on one line, at the top of their column, so the main current
    is a straight run across the picture and everything else hangs off it. That
    is the whole difference between a diagram you read and a field of boxes: a
    reader needs one line to follow before they can see what branches off it.
    """
    outgoing = {i: [] for i in ids}
    for a, b in fwd:
        outgoing[a].append(b)
    height = {i: 0 for i in ids}
    for i in sorted(ids, key=lambda k: -col[k]):     # sinks first
        height[i] = max([height[j] + 1 for j in outgoing[i]], default=0)
    longest = max([col[i] + height[i] for i in ids], default=0)
    return {i for i in ids if col[i] + height[i] == longest}


def order_columns(cols, fwd, spine):
    """The vertical order inside each column: spine on top, branches below.

    Barycentre passes -- each element wants to sit level with its neighbours in
    the previous column -- alternating forwards and backwards, which is the
    standard way to pull crossings out of a layered drawing. The spine is pinned
    to the top row throughout: a main line that wanders up and down between
    columns is exactly as hard to follow as no main line at all.
    """
    order = {c: sorted(members) for c, members in cols.items()}
    nbr_in, nbr_out = {}, {}
    for a, b in fwd:
        nbr_in.setdefault(b, []).append(a)
        nbr_out.setdefault(a, []).append(b)
    rank = {}
    for c in order:
        order[c] = sorted(order[c], key=lambda i: (0 if i in spine else 1, i))
        for k, i in enumerate(order[c]):
            rank[i] = k

    def barycentre(i, src):
        near = [rank[n] for n in src.get(i, []) if n in rank]
        return sum(near) / float(len(near)) if near else rank[i]

    for step in range(4):
        src = nbr_in if step % 2 == 0 else nbr_out
        for c in sorted(order, reverse=bool(step % 2)):
            order[c] = sorted(
                order[c],
                key=lambda i: (0 if i in spine else 1, barycentre(i, src), i),
            )
            for k, i in enumerate(order[c]):
                rank[i] = k
    return order


def hive_tree(ids):
    """The hive paths in the picture, as parent -> sorted children.

    Every ancestor of every cell is a hive, whether or not it holds a cell of its
    own: `/a/b/c/one` makes `/a`, `/a/b` and `/a/b/c` hives. Drawing only the
    direct parent was the defect reported as "hive in hive does not work properly
    yet" -- a colony is a tree, and a picture that shows only its leaves' parents
    shows none of it.
    """
    hives = set()
    for i in ids:
        parts = i.split("/")[:-1]          # every prefix above the cell itself
        for n in range(1, len(parts) + 1):
            hives.add("/".join(parts[:n]))
    kids = {"": []}
    for h in hives:
        kids.setdefault(h, [])
        parent = h.rsplit("/", 1)[0] if "/" in h else ""
        kids.setdefault(parent, []).append(h)
    for k in kids:
        kids[k] = sorted(kids[k])
    return kids


def split_tall_columns(order, size):
    """Break a column that has grown into a tower into side-by-side columns.

    Everything that shares a flow rank shares a column, and a colony has plenty
    of elements with no edge between them at all -- six independent hives all land
    in the first column and stack into a strip, which is precisely the shape this
    view was reported unusable for the first time. Nothing about that is a flow
    statement: they are peers, so they belong beside each other.

    The order inside the column is preserved, so the spine stays first and the
    barycentre work above is not undone.
    """
    out = []
    for c in sorted(order):
        members = order[c]
        wide = max(size[i][0] for i in members)
        tall = sum(size[i][1] for i in members) + GAP_Y * (len(members) - 1)
        if len(members) < 2 or tall <= TARGET_RATIO * wide:
            out.append(members)
            continue
        k = (TARGET_RATIO * tall / float(wide)) ** 0.5
        k = min(len(members), max(1, int(k) + (1 if k > int(k) else 0)))
        per = len(members) // k + (1 if len(members) % k else 0)
        for start in range(0, len(members), per):
            out.append(members[start:start + per])
    return out


def place_columns(order, size):
    """Put the ordered columns on the plane, wrapping when the run gets too long.

    A colony is a long thin thing: a four-cell chain drawn as pure left-to-right
    is a 918x92 stripe. Stack a few of those and the whole picture came out
    8232x848 -- a ratio of ten to one, which a screen can only show by shrinking
    every label past reading. The first version of this view failed the other way
    round, as one tall column; both are the same mistake, which is letting one
    axis carry all of the structure.

    So the columns wrap like text: left to right along a row, then down and back
    to the left. Within a row the flow still reads the way it runs, and a chain
    longer than the row is broken between columns -- never inside one, so no step
    of the flow is ever split.

    `TARGET_RATIO` is what "readable" means here: a block roughly twice as wide as
    it is tall, at every depth, so the whole nest stays close to the shape of the
    screen it is shown on.
    """
    groups = split_tall_columns(order, size)
    cols = list(range(len(groups)))
    order = {c: groups[c] for c in cols}
    col_w = {c: max(size[i][0] for i in order[c]) for c in cols}
    col_h = {
        c: sum(size[i][1] for i in order[c]) + GAP_Y * (len(order[c]) - 1)
        for c in cols
    }
    total_w = sum(col_w.values()) + GAP_X * max(0, len(cols) - 1)
    tallest = max(col_h.values())

    # How many rows to break into: with `k` rows the block is roughly
    # `total_w / k` wide and `k * tallest` high, and asking those to sit at the
    # target ratio gives `k = sqrt(total_w / (ratio * tallest))`. Deriving the
    # limit from the summed column AREA instead looks similar and is wrong -- a
    # chain of flat columns has almost no area, so every block became a tower,
    # which is the same unreadable shape this started from.
    limit = total_w
    if total_w > WRAP_MIN_W and total_w > TARGET_RATIO * tallest:
        rows = max(1, int(round((total_w / float(TARGET_RATIO * tallest)) ** 0.5)))
        limit = max(total_w / float(rows), max(col_w.values()))

    place = {}
    x, y_row, row_h = PAD_SIDE, PAD_TOP, 0
    for c in cols:
        if x > PAD_SIDE and x - PAD_SIDE + col_w[c] > limit:
            y_row += row_h + ROW_GAP
            x, row_h = PAD_SIDE, 0
        y = y_row
        for i in order[c]:
            place[i] = (x, y)
            y += size[i][1] + GAP_Y
        x += col_w[c] + GAP_X
        row_h = max(row_h, col_h[c])
    return place


def layout_block(hive, kids, ids_by_hive, pairs):
    """One hive and everything under it, laid out relative to its own frame.

    The same shape at every depth, which is what makes nesting work: a hive's
    elements are its own cells AND its child hives -- a child is one block with
    one size, and the parent never looks inside it. Elements are placed left to
    right by flow, stacked top to bottom within a column, spine first.

    Returns `(positions, width, height)` with (0, 0) at the frame's top-left
    corner, so a parent can place the block by its frame and nothing else.
    """
    children = kids.get(hive, [])
    sub = {c: layout_block(c, kids, ids_by_hive, pairs) for c in children}

    size = {i: (NODE_W, NODE_H) for i in ids_by_hive.get(hive, [])}
    for c in children:
        # A child's element is its frame plus the inset it will sit at, so no two
        # frames can touch however the columns fall.
        size[c] = (sub[c][1] + 2 * NEST, sub[c][2] + 2 * NEST)
    ids = sorted(size)
    if not ids:
        return {}, 0, 0

    projected = set()
    for a, b in pairs:
        ea, eb = element_of(a, hive), element_of(b, hive)
        if ea in size and eb in size and ea != eb:
            projected.add((ea, eb))

    col, fwd = columns_of(ids, sorted(projected))
    spine = spine_of(ids, fwd, col)
    cols = {}
    for i in ids:
        cols.setdefault(col[i], []).append(i)
    order = order_columns(cols, fwd, spine)

    place = place_columns(order, size)

    pos = {}
    for i in ids:
        px, py = place[i]
        if i in sub:
            for k, (rx, ry) in sub[i][0].items():
                pos[k] = (px + NEST + rx, py + NEST + ry)
        else:
            pos[i] = (px, py)

    # The frame: this hive's own cells padded, plus every child's frame grown by
    # the nesting inset. The same union `hive_frames` computes from the finished
    # positions, so the block reports exactly the rectangle that will be drawn.
    boxes = []
    own = [pos[i] for i in ids_by_hive.get(hive, [])]
    if own:
        boxes.append(box_of(own))
    for c in children:
        cx, cy = place[c]
        boxes.append((cx, cy, sub[c][1] + 2 * NEST, sub[c][2] + 2 * NEST))
    x0 = min(b[0] for b in boxes)
    y0 = min(b[1] for b in boxes)
    w = max(b[0] + b[2] for b in boxes) - x0
    h = max(b[1] + b[3] for b in boxes) - y0
    return {i: (p[0] - x0, p[1] - y0) for i, p in pos.items()}, w, h


def flow_layout(nodes, edges):
    """The picture with nothing moved: where every box would go on its own.

    A function of the WHOLE node set -- column ranks, barycentre order and block
    sizes all change when a single cell arrives. That is what it is for: it is
    where a cell nobody has placed goes. It is also exactly why nothing STORED is
    expressed against it. 1.x learned that the expensive way (GH #170): a hive row
    holding a POINT in this space walked off as soon as one cell was instantiated,
    and twelve of nineteen hand-placed frames in a real colony moved. Here nothing
    but a cell's own `x`/`y` is ever stored, and those are absolute.
    """
    ids_by_hive = {}
    for n in nodes:
        ids_by_hive.setdefault(hive_of(n["id"]), []).append(n["id"])
    kids = hive_tree([n["id"] for n in nodes])
    pairs = sorted({(e["from"], e["to"]) for e in edges})

    pos, _, _ = layout_block("", kids, ids_by_hive, pairs)
    return pos


def auto_layout(nodes, edges, saved):
    """Where every box sits: the flow layout, overruled by what is on record.

    Deterministic: same input, same output, so a changed picture means a changed
    colony -- or a hand that moved something.
    """
    pos = flow_layout(nodes, edges)
    for i, xy in saved.items():
        if i in pos:
            pos[i] = xy
    # Only a STORED position counts as placed by hand, and the frames are computed
    # over those cells ALONE: they are what a foreign hive occupies, and deriving
    # them from the cells still being settled would be circular.
    settle(pos, set(saved), hive_frames({i: pos[i] for i in saved if i in pos}))
    return pos


def settle(pos, placed, frames=None):
    """Push the cells nobody placed by hand out of the ones somebody did.

    In an arrangement made by hand every cell carries a stored position and the
    automatic layout is only a fallback. A cell that is instantiated later has
    no stored position, so it is placed by a layout computed for a picture that
    no longer exists -- and it lands on top of a pinned cell often enough that
    the first thing an operator does after wiring something is drag it out of
    the way. That is the work the layout is for.

    So: a hand-placed cell never moves, and a cell without a position is offered
    its computed spot first and the nearest free one after that. Search order is
    by distance and then by (dx, dy), which keeps it deterministic -- the same
    colony renders the same picture twice.

    `frames` are the rectangles the hand-placed cells give their hives, and a spot
    inside one that is NOT the cell's own or an ancestor of it counts as occupied
    as well. A cell drawn through a foreign frame is the same defect read from the
    other side: the frame is derived from its members, so a stranger inside it
    reads as a member, and the rectangle grows around a cell that does not belong
    to the group.

    A no-op on a colony nobody has arranged: with nothing pinned there is
    nothing to collide with, because the layout itself does not overlap.
    """
    step_x, step_y = NODE_W + GAP_X, NODE_H + GAP_Y
    frames = frames or {}

    def hits(box, x2, y2, w2, h2):
        x, y = box
        return x < x2 + w2 and x2 < x + NODE_W and y < y2 + h2 and y2 < y + NODE_H

    def free(box, taken, foreign):
        for (ox, oy) in taken:
            if hits(box, ox, oy, NODE_W, NODE_H):
                return False
        return not any(hits(box, *r) for r in foreign)

    def foreign_frames(i):
        own = hive_of(i)
        return [
            r
            for h, r in sorted(frames.items())
            if h and h != own and not own.startswith(h + "/")
        ]

    def outside_own(i, box):
        """0 while the box stays in its own hive's rectangle, 1 once it leaves.

        Sorted on FIRST inside a ring, which is what "nearest free spot,
        preferring inside its own hive" means: a cell shoved out of a crowd
        should give way into the group it belongs to rather than out of it, and
        only leave when the group has no room left.
        """
        r = frames.get(hive_of(i))
        return 0 if r is None or hits(box, *r) else 1

    taken = [pos[i] for i in sorted(placed) if i in pos]
    for i in sorted(k for k in pos if k not in placed):
        foreign = foreign_frames(i)
        if free(pos[i], taken, foreign):
            taken.append(pos[i])
            continue
        # Rings of grid steps around the computed spot, nearest first. Bounded:
        # a colony that fills eight rings in every direction has a layout
        # problem this cannot fix, and an unbounded search would hang the cell.
        spot = None
        for ring in range(1, 9):
            candidates = []
            for dx in range(-ring, ring + 1):
                for dy in range(-ring, ring + 1):
                    if max(abs(dx), abs(dy)) != ring:
                        continue
                    cand = (pos[i][0] + dx * step_x, pos[i][1] + dy * step_y)
                    # Right and down before left and up: the flow reads that
                    # way, so a cell that has to give way should give way along
                    # it rather than against it. Staying inside its own hive
                    # outranks all of that.
                    candidates.append(
                        (outside_own(i, cand), abs(dx) + abs(dy), dx < 0, dy < 0, cand)
                    )
            for c in sorted(candidates):
                cand = c[-1]
                if free(cand, taken, foreign):
                    spot = cand
                    break
            if spot:
                break
        pos[i] = spot or pos[i]
        taken.append(pos[i])


def box_of(points):
    """The padded frame around a set of cell positions."""
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    x = min(xs) - PAD_SIDE
    y = min(ys) - PAD_TOP
    return (x, y, (max(xs) + NODE_W + PAD_SIDE) - x, (max(ys) + NODE_H + PAD_BOT) - y)


def hive_frames(pos):
    """One rectangle per hive: `{hive: (x, y, w, h)}`.

    Its own cells, padded, unioned with every child's frame grown by the nesting
    inset. Recursive, so a hive that holds nothing but sub-hives still gets a
    frame, and an ancestor is strictly bigger than its child at every level.

    Derived and never stored, which is what makes a cell dragged out of a crowd
    GROW its hive -- and every hive ABOVE it -- instead of being stranded outside
    a stale rectangle. The client computes the same union during a drag, from the
    same constants, so the frames follow the cursor instead of waiting for the
    next tick.
    """
    kids = hive_tree(list(pos))
    own = {}
    for i in pos:
        own.setdefault(hive_of(i), []).append(pos[i])
    out = {}

    def rect(h):
        if h in out:
            return out[h]
        boxes = [box_of(own[h])] if own.get(h) else []
        for c in kids.get(h, []):
            cx, cy, cw, ch = rect(c)
            boxes.append((cx - NEST, cy - NEST, cw + 2 * NEST, ch + 2 * NEST))
        if not boxes:
            return (0, 0, 0, 0)
        x = min(b[0] for b in boxes)
        y = min(b[1] for b in boxes)
        out[h] = (x, y, max(b[0] + b[2] for b in boxes) - x,
                  max(b[1] + b[3] for b in boxes) - y)
        return out[h]

    for h in sorted(kids, key=lambda k: -k.count("/")):
        if h:
            rect(h)
    return out


def hive_boxes(pos):
    """The hive rectangles, ready to become objects."""
    frames = hive_frames(pos)
    boxes = []
    for h in sorted(frames):
        x, y, w, ht = frames[h]
        boxes.append(
            {
                "id": h,
                "name": h.rsplit("/", 1)[-1],
                "depth": h.count("/") + 1,
                "x": x,
                "y": y,
                "w": w,
                "h": ht,
            }
        )
    return boxes


def edge_lanes(edges):
    """A lane number per edge, centred within its endpoint pair.

    Two passes: number the edges inside each unordered pair, then shift the
    bundle so it straddles the centre line. Parallel edges between one pair then
    stay apart instead of overlapping.
    """
    groups = {}
    for e in edges:
        key = tuple(sorted((e["from"], e["to"])))
        groups.setdefault(key, []).append(e)
    for members in groups.values():
        n = len(members)
        for k, e in enumerate(members):
            e["lane"] = k - (n - 1) // 2
    return edges


def frame(nodes, hives):
    """The `viewBox`: the whole drawing, plus a margin.

    Without it the SVG shows the top-left corner of a canvas that is thousands of
    pixels tall, and since the element is exactly the size of its container there
    is nothing to scroll. Reported as "not usable", and rightly. With a viewBox
    the browser scales the whole arrangement into the frame on its own, before any
    JavaScript runs -- so the canvas is legible even if the client never loads.

    Pan and zoom then ride on TOP of this as the camera transform, which is why
    the frame is derived from the content and never from the camera.
    """
    xs = [n["x"] for n in nodes] + [h["x"] for h in hives]
    ys = [n["y"] for n in nodes] + [h["y"] for h in hives]
    if not xs:
        return (0, 0, NODE_W, NODE_H)
    right = max([n["x"] + NODE_W for n in nodes] + [h["x"] + h["w"] for h in hives])
    bottom = max([n["y"] + NODE_H for n in nodes] + [h["y"] + h["h"] for h in hives])
    x0 = min(xs) - PAD_SIDE
    y0 = min(ys) - PAD_TOP
    return (x0, y0, right - x0 + PAD_SIDE, bottom - y0 + PAD_BOT)


# ---------------------------------------------------------------------------
# Talking to the `web` cell


def tool_call(args):
    """One `object.*` call, as a UBF `tool_call` turn."""
    return {
        "origin": "assistant",
        "type": "tool_call",
        "id": uuid.uuid4().hex[:12],
        "text": json.dumps(args, sort_keys=True),
    }


def emission(route, turns, **header):
    """One message on `route`, carrying `turns` as its tool calls.

    `messages` is mandatory and not decoration: every body crossing the substrate
    is validated as a UBF document, and one without that slot is rejected as
    `invalid_ubf_body` -- the emission never reaches an edge, so it shows up as a
    dead letter from this cell and as a picture that silently stops updating.
    """
    head = {"route": route}
    head.update(header)
    return {"header": head, "messages": turns}


def compact(graph):
    """The projection this cell needs, and nothing else.

    It travels through `context` (see the module docstring), so every byte is one
    a header carries twice. Positional rows rather than objects for the same
    reason: `[[path, type], ...]` is roughly half of `[{"path":…,"type":…}, …]`
    for the same content.
    """
    nodes = []
    for n in graph.get("nodes") or []:
        if not isinstance(n, dict):
            continue
        path = str(n.get("path") or "").strip("/")
        if path:
            nodes.append([path, str(n.get("cell_type") or "")])
    edges = []
    for e in graph.get("edges") or []:
        if not isinstance(e, dict):
            continue
        mod = e.get("modifier")
        edges.append([
            str(e.get("id") or ""),
            str(e.get("from") or "").strip("/"),
            str(e.get("to") or "").strip("/"),
            str(e.get("condition") or ""),
            json.dumps(mod, sort_keys=True) if mod else "",
        ])
    return {"scope": str(graph.get("scope") or "/"), "nodes": nodes, "edges": edges}


def desired_objects(snap):
    """Every object this picture should hold, keyed by id.

    Positions are the flow layout's; the caller overrules them for whatever the
    display already knows, which is what keeps a drag.
    """
    nodes_in = snap.get("nodes") or []
    edges_in = snap.get("edges") or []

    edges = edge_lanes([
        {"id": e[0], "from": e[1], "to": e[2], "cond": e[3], "mod": e[4]}
        for e in edges_in
        if isinstance(e, list) and len(e) >= 5
    ])
    wired = {e["from"] for e in edges} | {e["to"] for e in edges}
    nodes = [
        {"id": n[0], "name": n[0].rsplit("/", 1)[-1], "type": n[1]}
        for n in nodes_in
        if isinstance(n, list) and len(n) >= 2 and n[0]
    ]
    for n in nodes:
        n["unwired"] = n["id"] not in wired
    return nodes, edges


def build(snap, saved):
    """The whole desired object set: `{id: {component, parent, ord, props}}`."""
    nodes, edges = desired_objects(snap)
    pos = auto_layout(nodes, [{"from": e["from"], "to": e["to"]} for e in edges], saved)
    for n in nodes:
        n["x"], n["y"] = pos.get(n["id"], (0, 0))
    hives = hive_boxes(pos)
    box = frame(nodes, hives)

    want = {}
    want[ROOT_ID] = {
        "component": "canvy-shell",
        "parent": None,
        "ord": 0,
        "props": {
            "title": snap.get("scope") or "/",
            "viewbox": "%d %d %d %d" % box,
            "cells": len(nodes),
            "hives": len(hives),
            "edges": len(edges),
            "nw": NODE_W,
            "nh": NODE_H,
            "pad_side": PAD_SIDE,
            "pad_top": PAD_TOP,
            "pad_bot": PAD_BOT,
            "nest": NEST,
        },
    }
    # Hives first, then edges, then cells: `ord` is the draw order, and a line
    # under a box reads as a line while a box under a line reads as a mistake.
    for h in hives:
        want[HIVE_PREFIX + h["id"]] = {
            "component": "canvy-hive",
            "parent": ROOT_ID,
            "ord": 100 + h["depth"],
            "props": {
                "path": h["id"],
                "name": h["name"],
                "depth": max(1, min(HIVE_DEPTH_TINTS, h["depth"])),
                "x": h["x"],
                "y": h["y"],
                "w": h["w"],
                "h": h["h"],
                "tx": h["x"] + 8,
                "ty": h["y"] + 18,
            },
        }
    for e in edges:
        want[EDGE_PREFIX + e["id"]] = {
            "component": "canvy-edge",
            "parent": ROOT_ID,
            "ord": 2000,
            "props": {
                "eid": e["id"],
                "from": e["from"],
                "to": e["to"],
                "lane": e.get("lane", 0),
                "cond": e["cond"],
                "mod": e["mod"],
            },
        }
    for n in nodes:
        fill, stroke = TYPE_COLOR.get(n["type"], DEFAULT_COLOR)
        want[NODE_PREFIX + n["id"]] = {
            "component": "canvy-node",
            "parent": ROOT_ID,
            "ord": 3000,
            "props": {
                "path": n["id"],
                "oid": NODE_PREFIX + n["id"],
                "name": n["name"],
                "type": n["type"],
                "x": n["x"],
                "y": n["y"],
                "w": NODE_W,
                "h": NODE_H,
                "fill": fill,
                "stroke": stroke,
                # A prop the `{{#if}}` has to read as absent when it is false, and
                # the empty string is how this template language spells that.
                "unwired": "1" if n["unwired"] else "",
            },
        }
    return want


def patches(want, have, bootstrap):
    """The calls that turn `have` into `want`, in an order the display accepts.

    Components before objects, the root before its children, the page after its
    root -- one bundle, applied in call order, so a fresh display and a running
    one take exactly the same path.
    """
    calls = []
    if bootstrap:
        for c in components():
            calls.append({"op": "component.define", **c})
        root = want[ROOT_ID]
        props = dict(root["props"])
        # The client rides in on the bootstrap and is never sent again: it is by
        # far the largest thing this cell says, and it does not change between
        # ticks. `object.update` merges per key, so leaving it out of every later
        # patch keeps it exactly as it is.
        props["client_css"] = CLIENT_CSS
        props["client_js"] = CLIENT_JS
        calls.append({
            "op": "object.create",
            "id": ROOT_ID,
            "component": root["component"],
            "ord": root["ord"],
            "props": props,
        })
        calls.append({"op": "page.set", "route": "/", "root": ROOT_ID,
                      "title": "canvy"})
    elif ROOT_ID in want:
        calls.append({"op": "object.update", "id": ROOT_ID,
                      "props": want[ROOT_ID]["props"]})

    for oid in sorted(k for k in want if k != ROOT_ID):
        spec = want[oid]
        if oid in have:
            calls.append({"op": "object.update", "id": oid, "props": spec["props"]})
        else:
            calls.append({
                "op": "object.create",
                "id": oid,
                "component": spec["component"],
                "parent": spec["parent"],
                "ord": spec["ord"],
                "props": spec["props"],
            })

    # What the colony no longer has. 1.x could not do this: a row naming a cell
    # that had vanished was indistinguishable from a rename, so the deletion was
    # an operator's button (`canvas:sweep`, GH #184). Here the objects ARE the
    # picture rather than a side table beside it -- an object with no cell behind
    # it is not stale bookkeeping, it is a box drawn for something that is gone.
    # Deleted leaf-first, because the display refuses to cascade.
    for oid in sorted((k for k in have if k != ROOT_ID and k not in want), reverse=True):
        calls.append({"op": "object.delete", "id": oid})
    return calls


# ---------------------------------------------------------------------------
# The three passes


def read_objects(body):
    """`{id: props}` out of a `query` answer, or None when it was not one."""
    msgs = body.get("messages") or []
    if not msgs:
        return None
    try:
        doc = json.loads(str(msgs[-1].get("text") or ""))
    except Exception:
        return None
    if not isinstance(doc, dict) or not isinstance(doc.get("objects"), list):
        return None
    out = {}
    for o in doc["objects"]:
        if isinstance(o, dict) and o.get("id"):
            props = o.get("props")
            out[str(o["id"])] = props if isinstance(props, dict) else {}
    return out


def saved_positions(have):
    """The positions the display already holds, in the layout's own space.

    This is the entire persistence story of a drag: the browser wrote `x` and `y`
    into the object, and the next tick reads them back and leaves them alone.
    """
    saved = {}
    for oid, props in have.items():
        if not oid.startswith(NODE_PREFIX):
            continue
        try:
            saved[oid[len(NODE_PREFIX):]] = (int(props.get("x")), int(props.get("y")))
        except (TypeError, ValueError):
            continue
    return saved


def main():
    doc = json.load(sys.stdin)
    body = doc.get("body") or {}
    header = (doc.get("envelope") or {}).get("header") or {}
    hop = header.get("hop") or {}
    ctx = header.get("context") or {}
    origin = str(ctx.get("canvy_origin") or "")

    # ---- pass 3 FIRST, because it is the terminating one.
    #
    # The display has answered a patch. There is nothing left to do, and this is
    # the only place that can say so: `canvy_origin` is stamped by the hive's
    # `./layout -> ./web` edge and travels back on the reply. Getting this wrong
    # is not a cosmetic bug -- see the GH #161 paragraph in the module docstring.
    if origin == "patch":
        return []

    # ---- pass 2: the display answered the query.
    if origin == "layout":
        raw = str(ctx.get("canvy_graph") or "")
        try:
            snap = json.loads(raw) if raw else None
        except Exception:
            snap = None
        if not isinstance(snap, dict) or not snap.get("nodes"):
            # No snapshot to draw. Silence rather than a half-picture: the timer
            # will bring the next one, and a display that emptied itself because
            # one message was malformed is worse than one that is a minute stale.
            return []

        have = read_objects(body)
        # A refusal is the BOOTSTRAP signal and the only one there is: a `web`
        # cell whose `pages` table has no `/` answers `query` with `invalid_input`.
        bootstrap = have is None
        if bootstrap:
            have = {}
        want = build(snap, saved_positions(have))
        calls = patches(want, have, bootstrap)
        if not calls:
            return []
        return [emission("patch", [tool_call(c) for c in calls])]

    # ---- pass 1: a snapshot arrived from the probe. Ask what the display holds.
    #
    # The graph goes out on `hop`, where the hive's edge picks it up and promotes
    # it into `context`; there is nowhere else to put it, because the display's
    # reply carries no body of ours and a `code` cell has no memory between calls.
    graph = body.get("graph")
    if not isinstance(graph, dict):
        return []
    snap = compact(graph)
    if not snap["nodes"]:
        return []
    return [
        emission(
            "read",
            [tool_call({"op": "query", "route": "/"})],
            canvy_graph=json.dumps(snap, sort_keys=True),
        )
    ]


if __name__ == "__main__":
    out = main()
    # A single emission is written as an object, several as an array -- and an
    # empty list stays an empty array, which is how a `code` cell says "nothing to
    # send" (`parse_stdout_json`: a top-level array of length 0 is zero emissions).
    # The `out[0]` shorthand this replaces raised IndexError on that case, which is
    # exactly the pass this cell most needs to survive.
    sys.stdout.write(json.dumps(out[0] if len(out) == 1 else out))
