//! The composition boundary itself: what crosses into the child, what comes
//! back, and what is refused.
//!
//! Three rules carry this module, and each of them is a test:
//!
//! 1. **The trace is carried, never regenerated.** One conversation stays one
//!    trace even though it is recorded in two message logs.
//! 2. **The TTL is decremented.** Crossing into another colony is a hop and
//!    costs one, so a sub-colony cycle dies exactly like any routing cycle. At
//!    zero the crossing is refused rather than made one last time.
//! 3. **Nothing else crosses unless it was declared.** `headers.context` moves
//!    only through the explicit `context_in` mapping; `headers.hop` never moves
//!    at all, because a single-hop compartment has no meaning on the far side.
//!
//! The reverse direction is opaque too: the child's context stays in the child.
//! The answer travels in the parent requester's own trace, so it has no use for
//! the child's internal bookkeeping.

use crate::subcolony::params::{RESERVED_CONTEXT_KEY, SubcolonyParams};
use meclaw_core::{Body, Message};
use serde_json::{Map, Value as JsonValue, json};

/// Wire version this build speaks. Asserted strictly on every frame.
pub const PROTOCOL_VERSION: u64 = 1;

/// A crossing that could not be made, carrying the code the cell will emit.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CrossingError {
    /// One of the cell's closed error-code set.
    pub error_code: &'static str,
    /// What went wrong, for the emission.
    pub detail: String,
}

impl CrossingError {
    fn new(error_code: &'static str, detail: impl Into<String>) -> Self {
        Self {
            error_code,
            detail: detail.into(),
        }
    }
}

/// Build the request frame for one inbound message.
///
/// `turn_id` is generated by the facade per request, not taken from the parent
/// message: a parent turn can fan out to several sub-colony calls, and a
/// correlation key that is not unique cannot correlate.
pub fn request_frame(
    msg: &Message,
    params: &SubcolonyParams,
    turn_id: &str,
) -> Result<JsonValue, CrossingError> {
    // Rule 2, and it comes first: a message with no hops left must not buy one
    // more by changing colonies.
    if msg.ttl == 0 {
        return Err(CrossingError::new(
            "ttl_exhausted",
            "the message has no hops left; crossing into the sub-colony would be one more",
        ));
    }
    let Body::Inline(body) = &msg.body else {
        return Err(CrossingError::new(
            "invalid_input",
            "a whole-body blob cannot cross the sub-colony boundary",
        ));
    };
    if !body.get("messages").is_some_and(JsonValue::is_array) {
        return Err(CrossingError::new(
            "invalid_input",
            "body: expected a UBF object with a messages[] array",
        ));
    }

    // Rule 3: start empty, add only what was declared.
    let mut context = Map::new();
    context.insert(RESERVED_CONTEXT_KEY.to_string(), json!(turn_id));
    for (from, to) in &params.context_in {
        if let Some(v) = msg.headers.context.get(from) {
            context.insert(to.clone(), v.clone());
        }
    }

    Ok(json!({
        "v": PROTOCOL_VERSION,
        "type": "message",
        // Rule 1.
        "trace_id": msg.trace_id.to_string(),
        // Rule 2.
        "ttl": msg.ttl - 1,
        "context": JsonValue::Object(context),
        "body": body.clone(),
    }))
}

/// Read a reply frame into the body the cell will emit.
///
/// Only the body crosses back. The child's `context` is deliberately dropped:
/// the reply rides the parent requester's trace, and copying the child's
/// bookkeeping into the parent tree would make the boundary leak in the
/// direction nobody asked it to.
pub fn reply_body(frame: &JsonValue) -> Result<JsonValue, CrossingError> {
    assert_protocol(frame)?;
    match frame.get("type").and_then(JsonValue::as_str) {
        Some("message") => frame
            .get("body")
            .filter(|b| b.is_object())
            .cloned()
            .ok_or_else(|| CrossingError::new("child_error", "reply frame carried no body object")),
        Some("error") => {
            let code = frame
                .get("error_code")
                .and_then(JsonValue::as_str)
                .unwrap_or("unknown");
            let detail = frame
                .get("detail")
                .and_then(JsonValue::as_str)
                .unwrap_or("no detail");
            Err(CrossingError::new(
                "child_error",
                format!("the sub-colony reported {code}: {detail}"),
            ))
        }
        other => Err(CrossingError::new(
            "child_error",
            format!("unexpected frame type {other:?}"),
        )),
    }
}

/// The correlation key of a frame, if it has one.
///
/// `None` means nobody is waiting for this frame — a child topology emitted it
/// on its own. That is a legitimate thing for a colony to do, and the cell
/// decides what to do with it (see `params.emit_to`).
pub fn correlation_key(frame: &JsonValue) -> Option<String> {
    frame
        .get("context")?
        .get(RESERVED_CONTEXT_KEY)?
        .as_str()
        .map(str::to_string)
}

/// Strict protocol assert (D4). Deliberately on the wire version and NOT on the
/// child's release version: a parent and a sealed child colony are expected to
/// run different builds, and that is the point of the boundary.
pub fn assert_protocol(frame: &JsonValue) -> Result<(), CrossingError> {
    match frame.get("v").and_then(JsonValue::as_u64) {
        Some(PROTOCOL_VERSION) => Ok(()),
        Some(other) => Err(CrossingError::new(
            "protocol_mismatch",
            format!("the sub-colony speaks protocol {other}, this build speaks {PROTOCOL_VERSION}"),
        )),
        None => Err(CrossingError::new(
            "protocol_mismatch",
            "the sub-colony sent a frame without a protocol version",
        )),
    }
}
