"""The surface: layout, markup, and the one write that keeps them honest.

THIS FILE IS THE SOURCE. `config.json` carries a copy of it in `script_inline`,
generated by `scripts/canvy_sync.py` and pinned by a test in
`crates/meclaw-cells/tests/canvy_template.rs`. Edit here, then run:

    python3 scripts/canvy_sync.py

Why the copy exists at all: a `code` cell's `script_path` is handed to the
interpreter verbatim with no working directory of its own (the factory ignores
`cell_dir` — `code` is stateless), so a relative path would resolve against the
daemon's cwd, and an absolute path baked into a template is the exported-tree
defect class of GH #20. So the runtime form is `script_inline`, and this file is
what a person reads, greps, diffs and runs:

    python3 templates/canvy/render/render.py < some-store-answer.json

# What this cell is, and what it is not

It is the whole picture. Every tag, every colour, every coordinate is decided
here, which is what makes a new object type a template change instead of a
release. The binary that serves it knows none of this.

It is NOT the owner of the topology. That comes from `/colony/graph`, by message,
into this hive's own store, on a timer — never read out of a database, and never
fetched inside a browser's request (a `/colony` reply arrives on a fresh envelope
with no context, so it could not be correlated back to the browser that asked).

# The two passes

Pass 1 (a request from the HTTP layer): remember what was asked in `hop`, emit one
`select` over the whole `canvas` table.

Pass 2 (the store's answer): compute the layout, render everything, emit the HTML
on the surface lane — and, if the request carried a move, emit the layout write in
the same pass. The box is rendered exactly where it is written, from one input, so
the picture and the database cannot disagree.
"""
import json
import sys
import uuid

# The layout constants, from the Python reference this ports (topology_html.py).
NODE_W, NODE_H = 150, 38
GAP_X, GAP_Y = 60, 40
PAD_TOP, PAD_SIDE, PAD_BOT = 30, 24, 24
# How wide a shelf of hives may grow before the next one wraps to a new row, and
# the air between two hive boxes. `SHELF_W` is a target and not a limit: a single
# hive wider than this still gets its own row rather than being cut.
SHELF_W = 2400
HIVE_GAP_X, HIVE_GAP_Y = 90, 80
# How much more room each level towards the ROOT gets, so an ancestor's frame
# strictly contains its descendants' instead of sharing an edge.
NEST_PAD = 14
# How many depths the stylesheet has a tint for. Deeper hives keep the last one.
# Ten, because a real colony gets deep: `/org/<org>/member/<who>/assistants/<name>/
# talky/keeper` is already eight, and two hives at different depths sharing a colour
# is exactly the thing the tint exists to prevent.
HIVE_DEPTH_TINTS = 10

# Fill and stroke per cell type. Ported verbatim from colony_topology.py so the
# shipped surface and the standalone renderer draw the same colony.
TYPE_COLOR = {
    "llm": ("#d6e4ff", "#4a6fa5"),
    "code": ("#e8e8e8", "#8a8a8a"),
    "file": ("#e8e8e8", "#8a8a8a"),
    "edit": ("#e8e8e8", "#8a8a8a"),
    "store": ("#ffe6cc", "#d79b00"),
    "proxy": ("#d5e8d4", "#82b366"),
    "timer": ("#fff2cc", "#d6b656"),
    "web_fetch": ("#f8cecc", "#b85450"),
    "web_search": ("#f8cecc", "#b85450"),
    "bash": ("#e1d5e7", "#9673a6"),
    "harness": ("#e1d5e7", "#9673a6"),
    "mcp": ("#e1d5e7", "#9673a6"),
    "vault": ("#f5f5f5", "#666666"),
    "subcolony": ("#dae8fc", "#6c8ebf"),
}
DEFAULT_COLOR = ("#ffffff", "#999999")


def esc(s):
    """Escape for an HTML text node or a double-quoted attribute.

    Everything rendered here came out of a database, and a cell path with a `<`
    in it must not be able to close a tag.
    """
    return (
        str(s)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )


def store_op(operation, **rest):
    """One store operation, on the lane the hive routes to its store.

    The four `moved_*`/`event` slots are set here, empty, on EVERY store emission
    and not only on the one that carries a drop. The hive's `./render -> ./store`
    edge promotes them into `context`, and an edge modifier that reads a hop field
    the emission does not have does not merely skip the promotion — the edge stops
    matching, so the emission dead-letters as `no_route`. That is how the position
    writes of a drop were silently lost while the picture still showed the box in
    its new place: the render reached the browser through a different edge, and only
    the two writes died.
    """
    args = {"operation": operation}
    args.update(rest)
    return {
        "header": {
            "route": "canvas",
            "event": "",
            "moved_id": "",
            "moved_x": "",
            "moved_y": "",
        },
        "messages": [
            {
                "origin": "assistant",
                "type": "tool_call",
                "id": uuid.uuid4().hex[:12],
                "text": json.dumps(args),
            }
        ],
    }


def surface_reply(slot):
    """The answer the HTTP layer is waiting for, on the egress lane.

    The lane is `./render -> .`: the answer is handed to this hive, finds no
    out-edge there, and leaves through the colony's egress door. The door is not
    a place any more — a marked message (`EgressPolicy::Marked`, and only the
    HTTP layer can mint the mark) leaves from whichever hive it ran out of graph
    at, which is what makes this hive installable by mutation at all (GH #163).
    Before that fix the lane had to be `-> /`, and no mutation may draw an edge
    that leaves its own subtree.

    `messages: []` is mandatory and not decoration. Every body crossing the
    substrate is validated as a UBF document, and one without that slot is
    rejected as `invalid_ubf_body` — the emission never reaches an edge, so it
    shows up as a dead letter from this cell and as a join that times out with no
    other trace. The surface payload rides alongside in its own `surface` slot.
    """
    return {"header": {"route": "surface"}, "messages": [], "surface": slot}


def last_text(body):
    """The text of the last turn, or "" — the store puts its answer there."""
    msgs = body.get("messages") or []
    return str(msgs[-1].get("text") or "") if msgs else ""


def rows_of(body):
    """The store's result, as rows, or None when it did not answer with rows.

    `None` here means "the store said something that is not a result set" — an
    error string, for instance. It must NOT be confused with "this is a fresh
    request": the passes are told apart by `context`, not by whether a body
    happens to parse. Getting that wrong once produced an infinite render/store
    loop that only stopped when the TTL ran out, and every store error would have
    produced it again.
    """
    try:
        v = json.loads(last_text(body) or "null")
    except Exception:
        return None
    return v if isinstance(v, list) else None


def fmt_scale(per_mille):
    """The camera's zoom as an SVG scale factor.

    Per-mille because a store column is `text`, `int` or `json` — there is no
    float, and a thousandth is finer than a mouse wheel can express.
    """
    z = max(100, min(4000, int(per_mille or 1000)))
    return ("%.3f" % (z / 1000.0)).rstrip("0").rstrip(".")


def as_doc(value):
    """A `json` column arrives as a string. Absent or unreadable → empty."""
    if isinstance(value, dict):
        return value
    if isinstance(value, str) and value.strip():
        try:
            v = json.loads(value)
            return v if isinstance(v, dict) else {}
        except Exception:
            return {}
    return {}


# --- the tree the colony graph describes -------------------------------------


def hive_of(path):
    """The parent path of a cell, without its leading slash. "" at the root."""
    p = path.strip("/")
    return p.rsplit("/", 1)[0] if "/" in p else ""


def flow_layers(ids, edges):
    """A layer per node: one below every node that feeds it.

    Longest-path from the sources, with a visit cap so a cycle cannot spin. A
    colony graph has cycles by design (every request/reply pair is one), so this
    is a drawing heuristic and not a topological sort.
    """
    incoming = {i: [] for i in ids}
    for e in edges:
        if e["from"] in incoming and e["to"] in incoming:
            incoming[e["to"]].append(e["from"])
    layer = {i: 0 for i in ids}
    for _ in range(min(len(ids), 64)):
        changed = False
        for i in ids:
            want = max([layer[s] + 1 for s in incoming[i]], default=0)
            if want > layer[i]:
                layer[i] = want
                changed = True
        if not changed:
            break
    return layer


def hive_block(members, layer):
    """One hive laid out on its own, relative to (0, 0): rows by flow rank.

    The flow layer is computed across the WHOLE graph, but it is applied inside
    one hive, so it has to be COMPRESSED here, not merely shifted. The global
    layer of a cell is the longest chain reaching it from anywhere, and a real
    colony has long chains: two cells in the same hive can carry layer 5 and
    layer 400 because one of them is downstream of a deep pipeline elsewhere.
    Shifting by the minimum leaves the 395 empty rows between them.

    Measured on a live 46-cell / 13-hive colony: y ran to 174828 with the raw
    layer, 52992 shifted, and 3384 ranked. What a hive's height should say is how
    many flow STEPS it has inside it, and ranking is what says that. The order is
    preserved, so a request still sits above the thing it asks.

    Returns `(relative positions, width, height)`.
    """
    rank = {lv: r for r, lv in enumerate(sorted({layer[i] for i in members}))}
    rows = {}
    for i in members:
        rows.setdefault(rank[layer[i]], []).append(i)
    rel = {}
    width = 0
    for lv in sorted(rows):
        x = 0
        for i in rows[lv]:
            rel[i] = (x, lv * (NODE_H + GAP_Y))
            x += NODE_W + GAP_X
        width = max(width, x - GAP_X)
    height = (max(rows) + 1) * (NODE_H + GAP_Y) - GAP_Y
    return rel, width, height


def hive_tree(ids):
    """The hive paths in the picture, as parent -> sorted children.

    Every ancestor of every cell is a hive, whether or not it holds a cell of its
    own: `/a/b/c/one` makes `/a`, `/a/b` and `/a/b/c` hives. Drawing only the
    direct parent was the defect reported as "hive in hive does not work properly
    yet" — a colony is a tree, and a picture that shows only its leaves' parents
    shows none of it.
    """
    hives = set()
    for i in ids:
        parts = i.split("/")[:-1]          # every prefix above the cell itself
        for n in range(1, len(parts) + 1):
            hives.add("/".join(parts[:n]))
    kids = {"": []}
    for h in hives:
        kids.setdefault(h, [])
        parent = h.rsplit("/", 1)[0] if "/" in h else ""
        kids.setdefault(parent, []).append(h)
    for k in kids:
        kids[k] = sorted(kids[k])
    return kids


def own_cells(ids_by_hive, hive):
    """The cells whose immediate parent is `hive`."""
    return ids_by_hive.get(hive, [])


def layout_subtree(hive, kids, ids_by_hive, layer):
    """Lay out one hive and everything under it, relative to (0, 0).

    The shape is the same at every depth, which is what makes nesting work at all:
    a hive's OWN cells go on top as rows by flow rank, its child hives are packed
    into shelves underneath, and the whole thing reports one size. A parent then
    packs its children by that size without knowing anything about their insides.

    Returns `(positions, width, height)` — positions keyed by cell id.
    """
    pos = {}
    members = sorted(own_cells(ids_by_hive, hive), key=lambda i: (layer[i], i))
    width = height = 0
    if members:
        rel, w, h = hive_block(members, layer)
        for i, (rx, ry) in rel.items():
            pos[i] = (rx, ry)
        width, height = w, h

    children = kids.get(hive, [])
    if children:
        # A child hive needs room for its own frame on every side, so it is inset
        # by one padding step; that inset is also what keeps the derived boxes
        # strictly nested instead of sharing an edge.
        shelf_y = height + (HIVE_GAP_Y if members else 0)
        shelf_x, shelf_h = 0, 0
        for child in children:
            cpos, cw, ch = layout_subtree(child, kids, ids_by_hive, layer)
            if shelf_x > 0 and shelf_x + cw > SHELF_W:
                shelf_y += shelf_h + HIVE_GAP_Y
                shelf_x, shelf_h = 0, 0
            for i, (rx, ry) in cpos.items():
                pos[i] = (shelf_x + rx + PAD_SIDE, shelf_y + ry + PAD_TOP)
            shelf_x += cw + 2 * PAD_SIDE + HIVE_GAP_X
            shelf_h = max(shelf_h, ch + 2 * PAD_TOP)
            width = max(width, shelf_x - HIVE_GAP_X)
        height = shelf_y + shelf_h
    return pos, width, height


def auto_layout(nodes, edges, saved, hive_at=None):
    """Where every box sits. A saved position always wins.

    Three levels, and each one only knows about the next: cells inside a hive are
    rows by flow depth, so a request sits above the thing it asks; a hive's child
    hives are packed into shelves below its own cells; the top level packs whatever
    has no parent. Recursive, so depth costs nothing.

    Stacking everything in one column was the first version and was reported
    unusable: 14 hives became a 3672-pixel strip two boxes wide, every hive at the
    same x, one bit of information where a screen offers two dimensions. Drawing
    only a cell's DIRECT parent was the second: a colony is a tree and the picture
    showed none of it.

    Deterministic: same input, same output, so a changed picture means a changed
    colony.
    """
    ids = [n["id"] for n in nodes]
    layer = flow_layers(ids, edges)
    hive_at = hive_at or {}
    ids_by_hive = {}
    for n in nodes:
        ids_by_hive.setdefault(hive_of(n["id"]), []).append(n["id"])
    kids = hive_tree(ids)

    pos = {}
    # The root level: cells with no hive at all, then every top-level hive.
    shelf_x, shelf_y, shelf_h = PAD_SIDE, PAD_TOP, 0
    loose = sorted(own_cells(ids_by_hive, ""), key=lambda i: (layer[i], i))
    if loose:
        rel, w, h = hive_block(loose, layer)
        for i, (rx, ry) in rel.items():
            pos[i] = (shelf_x + rx, shelf_y + ry)
        shelf_y += h + HIVE_GAP_Y

    for hive in kids.get("", []):
        sub, w, h = layout_subtree(hive, kids, ids_by_hive, layer)
        if shelf_x > PAD_SIDE and shelf_x + w > SHELF_W:
            shelf_y += shelf_h + HIVE_GAP_Y
            shelf_x, shelf_h = PAD_SIDE, 0
        ox, oy = shelf_x, shelf_y
        for i, (rx, ry) in sub.items():
            pos[i] = (ox + rx, oy + ry)
        shelf_x += w + HIVE_GAP_X
        shelf_h = max(shelf_h, h)

    # A hive somebody moved keeps the place they put it, and takes its WHOLE
    # subtree along. What is stored is an offset, never the rectangle: the
    # rectangle stays derived, which is what lets a cell dragged out of a crowd
    # grow its hive instead of being stranded outside a stale frame. Applied
    # shallowest-first, so moving a parent and then a child reads as the child
    # having been placed inside the parent's new position.
    # The SAME `deepest` the renderer uses, or the padding differs between the box
    # that was dragged and the box the delta is computed from, and every hive move
    # lands a few pixels off.
    deepest = max((i.count("/") for i in pos), default=1)
    for hive in sorted(hive_at, key=lambda h: (h.count("/"), h)):
        members = [i for i in pos if i.startswith(hive + "/")]
        if not members:
            continue
        cur = box_of([pos[i] for i in members], hive.count("/") + 1, deepest)
        dx = hive_at[hive][0] - cur[0]
        dy = hive_at[hive][1] - cur[1]
        for i in members:
            pos[i] = (pos[i][0] + dx, pos[i][1] + dy)

    # Precedence, and it only reads one way: a cell that somebody placed by hand
    # keeps its place, then the offset of its hive, then the automatic layout. A
    # hive move that silently undid every hand-placed cell inside it would make
    # the two gestures fight each other.
    for i, xy in saved.items():
        if i in pos:
            pos[i] = xy
    return pos


def box_of(points, depth, deepest=None):
    """The frame around a set of cell positions, padded for its depth.

    The padding grows towards the ROOT: an ancestor gets strictly more room than
    its descendants, which is what makes a parent's frame strictly CONTAIN a
    child's instead of sharing an edge with it. Two boxes that touch read as two
    boxes bumping into each other; nesting has to be visible without measuring.
    """
    deepest = depth if deepest is None else deepest
    step = max(0, deepest - depth) * NEST_PAD
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    x = min(xs) - PAD_SIDE - step
    y = min(ys) - PAD_TOP - step
    w = (max(xs) + NODE_W + PAD_SIDE + step) - x
    h = (max(ys) + NODE_H + PAD_BOT + step) - y
    return (x, y, w, h)


def hive_boxes(nodes, pos):
    """One box per hive, derived from where its members ended up.

    Derived and never stored, which is what makes dragging a cell out of a crowd
    GROW its hive instead of stranding the cell outside a stale rectangle — and
    what makes a parent follow when a hive inside it moves.

    A hive's members are every cell BELOW it, at any depth, not only its direct
    children: that is the whole of hive-in-hive. `/a` is the frame around
    everything under `/a`, `/a/b` the frame around everything under `/a/b`, and a
    hive that holds nothing but sub-hives still gets a frame — previously it got
    none, so the deepest structure in the colony was the only structure drawn.
    """
    groups = {}
    for n in nodes:
        parts = n["id"].split("/")[:-1]
        for k in range(1, len(parts) + 1):
            groups.setdefault("/".join(parts[:k]), []).append(pos[n["id"]])
    if not groups:
        return []
    deepest = max(h.count("/") + 1 for h in groups)
    boxes = []
    for h in sorted(groups):
        depth = h.count("/") + 1
        x, y, w, ht = box_of(groups[h], depth, deepest)
        boxes.append(
            {
                "id": h,
                "name": h.rsplit("/", 1)[-1],
                "depth": depth,
                "x": x,
                "y": y,
                "w": w,
                "h": ht,
            }
        )
    return boxes


def edge_lanes(edges):
    """A lane number per edge, centred within its endpoint pair.

    Two passes, the same two the reference viewer did: number the edges inside
    each unordered pair, then shift the bundle so it straddles the centre line.
    Parallel edges between one pair then stay apart instead of overlapping.
    """
    groups = {}
    for e in edges:
        key = tuple(sorted((e["from"], e["to"])))
        groups.setdefault(key, []).append(e)
    for members in groups.values():
        n = len(members)
        for k, e in enumerate(members):
            e["lane"] = k - (n - 1) // 2
    return edges


# --- markup -------------------------------------------------------------------


def node_svg(n):
    # `data-node` is what the drag hook grabs; `data-from`/`data-to` on an edge is
    # how it finds the lines belonging to a box without being told.
    return (
        '<g class="node" data-node="%s" data-w="%d" data-h="%d" '
        'transform="translate(%d,%d)">'
        '<rect width="%d" height="%d" rx="6" fill="%s" stroke="%s"/>'
        '<text class="nm" x="8" y="16">%s</text>'
        '<text class="ty" x="8" y="30">%s</text>'
        "</g>"
    ) % (
        esc(n["id"]),
        NODE_W,
        NODE_H,
        n["x"],
        n["y"],
        NODE_W,
        NODE_H,
        esc(n["fill"]),
        esc(n["stroke"]),
        esc(n["name"]),
        esc(n["type"]),
    )


def hive_svg(h):
    # `depth-N` is what the stylesheet tints. Clamped, because a tree deeper than
    # the palette should keep the deepest colour rather than fall back to none —
    # a hive with no tint would read as "not a hive".
    depth = max(1, min(HIVE_DEPTH_TINTS, h["depth"]))
    return (
        '<g class="hive depth-%d" data-hive="%s">'
        '<rect x="%d" y="%d" width="%d" height="%d" rx="10"/>'
        '<text x="%d" y="%d">%s</text>'
        "</g>"
    ) % (
        depth,
        esc(h["id"]),
        h["x"],
        h["y"],
        h["w"],
        h["h"],
        h["x"] + 8,
        h["y"] + 18,
        esc(h["name"]),
    )


def edge_svg(e):
    """An edge as its ENDPOINTS, not as a finished path.

    There is deliberately no `d` attribute here. The orthogonal routing lives in
    the client (`client/surface.js`) because it is presentation, and a `d`
    computed on both sides would be one algorithm in two languages. The client
    reads these attributes and draws.
    """
    return (
        '<path class="edge" data-edge="%s" data-from="%s" data-to="%s" '
        'data-lane="%d" data-cond="%s"/>'
    ) % (
        esc(e["id"]),
        esc(e["from"]),
        esc(e["to"]),
        e.get("lane", 0),
        esc(e.get("condition") or ""),
    )


def frame(nodes, hives):
    """The `viewBox`: the whole drawing, plus a margin.

    Without it the SVG shows the top-left corner of a canvas that is thousands of
    pixels tall, and since the element is exactly the size of its container there
    is nothing to scroll. Reported as "not usable", and rightly: a picture you
    cannot see the bottom of is not a picture. With a viewBox the browser scales
    the whole arrangement into the frame on its own, before any JavaScript runs —
    so the canvas is legible even if the client never loads.

    Zoom and pan then ride on TOP of this as the camera transform, which is why
    the frame is derived from the content and never from the camera.
    """
    xs = [n["x"] for n in nodes] + [h["x"] for h in hives]
    ys = [n["y"] for n in nodes] + [h["y"] for h in hives]
    if not xs:
        return (0, 0, NODE_W, NODE_H)
    right = max([n["x"] + NODE_W for n in nodes] + [h["x"] + h["w"] for h in hives])
    bottom = max([n["y"] + NODE_H for n in nodes] + [h["y"] + h["h"] for h in hives])
    x0 = min(xs) - PAD_SIDE
    y0 = min(ys) - PAD_TOP
    return (x0, y0, right - x0 + PAD_SIDE, bottom - y0 + PAD_BOT)


def render(nodes, hives, edges, camera, title):
    box = frame(nodes, hives)
    parts = [
        # `id` + `phx-hook` are the contract with `client/surface.js`, and they are
        # load-bearing rather than cosmetic: a LiveView hook mounts only on an
        # element that carries BOTH. Without them the client never runs — no edge
        # gets its `d` (the server deliberately sends endpoints, not paths) and
        # nothing can be dragged. That was the state of every join until
        # 2026-08-17, with all the server-side tests green, because they all
        # asserted about the markup and none about the seam.
        '<div class="canvy" id="canvy" phx-hook="Canvy" data-title="%s">' % esc(title),
        '<svg class="stage" xmlns="http://www.w3.org/2000/svg" '
        'viewBox="%d %d %d %d" preserveAspectRatio="xMidYMid meet">' % box,
        # The camera is a transform on the viewport group, so pan and zoom compose
        # with the frame above instead of fighting it. Identity at (0,0,1000).
        '<g class="viewport" data-cx="%d" data-cy="%d" data-cz="%d" '
        'transform="translate(%d,%d) scale(%s)">'
        % (
            camera[0],
            camera[1],
            camera[2],
            camera[0],
            camera[1],
            fmt_scale(camera[2]),
        ),
        '<g class="hives">',
    ]
    parts.extend(hive_svg(h) for h in hives)
    parts.append('</g><g class="edges">')
    parts.extend(edge_svg(e) for e in edges)
    parts.append('</g><g class="nodes">')
    parts.extend(node_svg(n) for n in nodes)
    parts.append("</g></g></svg>")
    parts.append(
        '<div class="legend">%d cells, %d hives, %d edges</div>'
        % (len(nodes), len(hives), len(edges))
    )
    parts.append("</div>")
    return "".join(parts)


# --- the two passes -----------------------------------------------------------


def main():
    doc = json.load(sys.stdin)
    body = doc.get("body") or {}
    env = doc.get("envelope") or {}
    header = env.get("header") or {}
    hop = header.get("hop") or {}

    ctx = header.get("context") or {}

    # WHICH PASS THIS IS, decided by edge authority and nothing else.
    #
    # `canvy_origin` is stamped by the hive's `./render -> ./store` edge, so it is
    # on the store's reply and on nothing an HTTP request carries. Deciding this by
    # inspecting the body instead — "did it parse as rows?" — turned every store
    # error into an infinite render/store loop that stopped only at the TTL. A
    # discriminator has to be unambiguous, and only an edge can make it so.
    if str(ctx.get("canvy_origin") or "") != "render":
        # ---- pass 1: a request came in. Ask the store for everything.
        req = body.get("surface") or {}
        # `columns` is REQUIRED by the store — a select without it answers
        # "missing columns array", which is how the loop above was found.
        out = store_op(
            "select",
            table="canvas",
            columns=["kind", "id", "x", "y", "z", "doc"],
            limit=100000,
        )
        # The request rides along in `hop`, and the hive's `./render -> ./store`
        # edge promotes it into `context`. That promotion is not decoration: `hop`
        # survives exactly ONE edge, and pass 2 is two edges away
        # (render -> store -> render). Carrying it in `hop` alone looked right and
        # silently lost every drop — the box came back at its automatic position.
        out["header"]["event"] = str(req.get("event") or "")
        value = req.get("value") or {}
        out["header"]["moved_id"] = str(value.get("id") or "")
        out["header"]["moved_x"] = str(value.get("x") or "")
        out["header"]["moved_y"] = str(value.get("y") or "")
        out["header"]["cam"] = json.dumps(value.get("camera") or {})
        return [out]

    # ---- pass 2: the store answered.
    rows = rows_of(body)
    if hop.get("error_code"):
        # A refused write. One corrective render, because a picture claiming a
        # position the database does not hold is worse than a visible failure.
        return [
            surface_reply(
                {"error": "the canvas store refused a write: %s" % hop.get("error_code")}
            )
        ]

    if rows is None:
        # The store answered, and it was not a result set. One visible failure,
        # never a retry: a retry against a store that just refused is a loop.
        return [
            surface_reply(
                {"error": "the canvas store did not return rows: %s" % last_text(body)[:200]}
            )
        ]

    saved = {}
    hive_at = {}
    camera = (0, 0, 1000)
    graph = {}
    for r in rows:
        kind = r.get("kind")
        if kind == "node":
            try:
                saved[str(r.get("id"))] = (int(r.get("x") or 0), int(r.get("y") or 0))
            except (TypeError, ValueError):
                continue
        elif kind == "hive":
            # Where a GROUP was put. Same shape as a node row, different `kind`.
            try:
                hive_at[str(r.get("id"))] = (int(r.get("x") or 0), int(r.get("y") or 0))
            except (TypeError, ValueError):
                continue
        elif kind == "camera":
            try:
                camera = (
                    int(r.get("x") or 0),
                    int(r.get("y") or 0),
                    int(r.get("z") or 1000),
                )
            except (TypeError, ValueError):
                pass
        elif kind == "graph":
            graph = as_doc(r.get("doc"))

    raw_nodes = graph.get("nodes") or []
    raw_edges = graph.get("edges") or []
    if not isinstance(raw_nodes, list) or not isinstance(raw_edges, list):
        return [surface_reply({"error": "the topology snapshot is malformed"})]
    if not raw_nodes:
        return [
            surface_reply(
                {
                    "error": "no topology snapshot yet — the refresh timer has not "
                    "run, or /colony/graph answered nothing"
                }
            )
        ]

    edges = edge_lanes(
        [
            {
                "id": str(e.get("id") or ""),
                "from": str(e.get("from") or "").strip("/"),
                "to": str(e.get("to") or "").strip("/"),
                "condition": e.get("condition"),
            }
            for e in raw_edges
            if isinstance(e, dict)
        ]
    )

    # A move overrides both the saved position and the automatic one. This is
    # what keeps the picture and the database from disagreeing: the box is
    # rendered where it is written, from ONE input.
    # From `context`, not from `hop`: see the promotion in the hive's edge.
    moved_id = str(ctx.get("canvy_moved_id") or "")
    event = str(ctx.get("canvy_event") or "")
    writes = []
    if moved_id and event == "hive:moved":
        # A group was dropped. One row for the group — never one per member: a
        # 20-cell hive would otherwise cost 40 store round trips on an
        # interactive path, and the members' own rows would then have to be kept
        # consistent with a box nobody stores.
        try:
            hx, hy = int(ctx.get("canvy_moved_x")), int(ctx.get("canvy_moved_y"))
        except (TypeError, ValueError):
            hx = hy = None
        if hx is not None:
            hive_at[moved_id] = (hx, hy)
            writes.append(
                store_op("delete", table="canvas", where={"kind": "hive", "id": moved_id})
            )
            writes.append(
                store_op(
                    "insert",
                    table="canvas",
                    row={"kind": "hive", "id": moved_id, "x": hx, "y": hy},
                )
            )
    elif moved_id:
        try:
            mx, my = int(ctx.get("canvy_moved_x")), int(ctx.get("canvy_moved_y"))
        except (TypeError, ValueError):
            mx = my = None
        if mx is not None:
            saved[moved_id] = (mx, my)
            # Delete then insert, in one emission and in that order: a position is
            # presentation state, so the row is REPLACED rather than appended. The
            # no-delete promise protects what was said and what was learned; where
            # a rectangle sits is neither.
            writes.append(
                store_op("delete", table="canvas", where={"kind": "node", "id": moved_id})
            )
            writes.append(
                store_op(
                    "insert",
                    table="canvas",
                    row={"kind": "node", "id": moved_id, "x": mx, "y": my},
                )
            )

    nodes = []
    for n in raw_nodes:
        if not isinstance(n, dict):
            continue
        path = str(n.get("path") or "").strip("/")
        if not path:
            continue
        ctype = str(n.get("cell_type") or "")
        fill, stroke = TYPE_COLOR.get(ctype, DEFAULT_COLOR)
        nodes.append(
            {
                "id": path,
                "name": path.rsplit("/", 1)[-1],
                "type": ctype,
                "fill": fill,
                "stroke": stroke,
            }
        )

    pos = auto_layout(nodes, edges, saved, hive_at)
    for n in nodes:
        n["x"], n["y"] = pos[n["id"]]
    hives = hive_boxes(nodes, pos)

    html = render(nodes, hives, edges, camera, graph.get("scope") or "/")
    return writes + [surface_reply({"html": html})]


if __name__ == "__main__":
    out = main()
    sys.stdout.write(json.dumps(out if len(out) > 1 else out[0]))
