"""The topology snapshot: ask /colony/graph, hand the answer to the layout.

THIS FILE IS THE SOURCE. `config.json` carries a copy in `script_inline`,
generated by `scripts/canvy_sync.py` and pinned by a test. Edit here, then run:

    python3 scripts/canvy_sync.py

# Why this is a separate cell on a timer, and not a leg of a request path

A reply from a `/colony/*` endpoint is built as a **fresh** message: new trace,
no `parent_message_id`, no `correlation_id`, and **no `context`**
(`crates/meclaw-colony/src/colony_dispatch.rs`, `emit_reply_or_done`). So a leg
through `/colony/graph` inside a browser's request would come back with nothing
that identifies the browser, and the answer could not be routed to whoever asked.
A cell has no way to say WHICH browser asked, so the pairing has to live
somewhere. An on-disk pointer would only be sound under a lease that guarantees
one request at a time -- with several browsers it is not sound, which is why the
correlation travels in the message instead.

So the snapshot is taken on a timer, where **nothing is waiting**. A colony's
graph changes on mutation, not on mouse movement, so a periodic snapshot is the
honest model rather than a compromise. And since 2.0.0 nothing about a browser's
request touches this cell at all: the display is a `web` cell that serves its
pages out of a materialised tree, so a page load costs no cell call whatsoever.

# Two passes

Pass 1 (the timer ticked, or somebody asked on `in_refresh`): emit one read to
`/colony/graph`. Nothing else.

Pass 2 (the colony answered): hand the graph to `./layout` on the `snapshot`
lane, unread. What a picture needs out of it is the layout cell's business, and
this cell deliberately knows none of it -- it is the lane to the colony's own
read-only topology endpoint and nothing more.

There is no third pass. The layout never answers this cell, so there is no
acknowledgement to recognise: the loop 1.x had to guard against (GH #161, one
tick becoming two becoming four) cannot form here, because the reply flows on to
the display instead of back.
"""
import json
import sys


def main():
    doc = json.load(sys.stdin)
    body = doc.get("body") or {}

    # ---- pass 2: the colony's graph reply nests its answer under a `graph` slot
    # -- verified against a live reply, because the first version of this cell
    # looked for `nodes` at the top level and therefore re-asked on every tick
    # without ever producing a snapshot.
    #
    # A body check and not a header check, and that is forced: a `/colony/*` reply
    # arrives on a fresh envelope with no `context` and no `hop` of ours, so there
    # is nothing else to look at.
    reply = body.get("graph")
    if isinstance(reply, dict) and isinstance(reply.get("nodes"), list):
        return [{
            "header": {"route": "snapshot"},
            "messages": [],
            "graph": {
                "scope": reply.get("scope") or "/",
                "nodes": reply.get("nodes") or [],
                "edges": reply.get("edges") or [],
            },
        }]

    # ---- pass 1: ask.
    #
    # The target is NOT set here and cannot be: a `code` cell's stdout is a body,
    # and where it goes is the edge's decision. The lane `./probe -> /colony/graph`
    # is declared by this hive's OWN config.json and travels with the template
    # (GH #163). `/colony/graph` is one of the absolute endpoints a mutation may
    # draw: it is not a cell but the colony's read-only topology endpoint, and it
    # is the sanctioned way to learn topology -- § Database isolation forbids
    # reading `colony.db`, so refusing the lane would only have pushed somebody
    # there. `MUTATION_DRAWABLE_VIRTUAL_ENDPOINTS` enumerates the drawable
    # endpoints by name; the counts-never-content `/colony/ledger` joined it with
    # GH #267.
    #
    # `reply_to` is not set here either, and also cannot be: the substrate stamps
    # every cell emission with the emitting cell's own path, so the colony's answer
    # comes back to this cell without anybody asking for it.
    return [{"header": {"route": "ask_colony"}, "messages": [], "query": {"scope": "/"}}]


if __name__ == "__main__":
    out = main()
    # A single emission is written as an object, several as an array -- and an
    # empty list stays an empty array, which is how a `code` cell says "nothing to
    # send" (`parse_stdout_json`: a top-level array of length 0 is zero emissions).
    sys.stdout.write(json.dumps(out[0] if len(out) == 1 else out))
