"""The topology snapshot: ask /colony/graph, write the answer into the store.

THIS FILE IS THE SOURCE. `config.json` carries a copy in `script_inline`,
generated by `scripts/canvy_sync.py` and pinned by a test. Edit here, then run:

    python3 scripts/canvy_sync.py

# Why this is a separate cell on a timer, and not a leg of the render path

A reply from a `/colony/*` endpoint is built as a **fresh** message: new trace,
no `parent_message_id`, no `correlation_id`, and **no `context`**
(`crates/meclaw-colony/src/colony_dispatch.rs`, `emit_reply_or_done`). So a leg
through `/colony/graph` inside a browser's request would come back with nothing
that identifies the browser, and the answer could not be routed to whoever asked.
`templates/builder-hive` hits the same wall and works around it with an on-disk
in-flight pointer, which is only sound because a lease guarantees a single request
at a time — with several browsers it is not sound.

So the snapshot is taken on a timer, where **nothing is waiting**, and rendering
reads only this hive's own store. A colony's graph changes on mutation, not on
mouse movement, so a periodic snapshot is the honest model rather than a
compromise.

# Three passes, and the third one is the one that matters

Pass 1 (the timer ticked): emit one read to `/colony/graph`. Nothing else.
Pass 2 (the colony answered): replace the single `kind='graph'` row.
Pass 3 (the store answered): emit NOTHING. This pass is the whole reason the
cell needs a discriminator at all — see below.
"""
import json
import sys
import uuid

def store_op(operation, **rest):
    args = {"operation": operation}
    args.update(rest)
    return {
        "header": {"route": "snapshot"},
        "messages": [
            {
                "origin": "assistant",
                "type": "tool_call",
                "id": uuid.uuid4().hex[:12],
                "text": json.dumps(args),
            }
        ],
    }


def main():
    doc = json.load(sys.stdin)
    body = doc.get("body") or {}
    ctx = ((doc.get("envelope") or {}).get("header") or {}).get("context") or {}

    # ---- pass 3 FIRST, because it is the terminating one.
    #
    # The store has answered a write. There is nothing left to do, and this is the
    # only place that can say so: `canvy_origin` is stamped by the hive's
    # `./probe -> ./store` edge and travels back on the store's reply, exactly as
    # it does for the render cell.
    #
    # Getting this wrong is not a cosmetic bug and it is worth the paragraph. Pass
    # 2 emits TWO store ops (delete + insert); the store answers each one; and
    # before this check existed each answer fell through to "the timer ticked, ask
    # again" — so one tick became two asks, two became four, and the colony's
    # routing loop wedged on a full mailbox inside 20 seconds with an empty
    # dead-letter queue (GH #161). A cell that cannot recognise a reply to its own
    # write has no way to stop.
    if str(ctx.get("canvy_origin") or "") == "probe":
        return []

    # ---- pass 2: the colony's graph reply nests its answer under a `graph` slot —
    # verified against a live reply, because the first version of this cell looked
    # for `nodes` at the top level and therefore re-asked on every tick without
    # ever writing a snapshot.
    #
    # A body check here and not a header check, and that is forced: a `/colony/*`
    # reply arrives on a fresh envelope with no `context` and no `hop` of ours, so
    # there is nothing else to look at. That is also why the pass-3 check above has
    # to come first — the fresh envelope means "no context" cannot mean "the store
    # answered".
    reply = body.get("graph")
    if isinstance(reply, dict) and isinstance(reply.get("nodes"), list):
        graph = {
            "scope": reply.get("scope") or "/",
            "nodes": reply.get("nodes") or [],
            "edges": reply.get("edges") or [],
        }
        # Replace, never append: this is a snapshot, and two snapshots would make
        # the renderer pick one arbitrarily.
        return [
            store_op("delete", table="canvas", where={"kind": "graph", "id": "colony"}),
            store_op(
                "insert",
                table="canvas",
                row={"kind": "graph", "id": "colony", "doc": json.dumps(graph)},
            ),
        ]

    # ---- pass 1: the timer ticked. Ask.
    #
    # The target is NOT set here and cannot be: a `code` cell's stdout is a body,
    # and where it goes is the edge's decision. The lane `./probe -> /colony/graph`
    # is granted by the PARENT config.json — an absolute endpoint is out of scope
    # for any mutation (`scope_out_of_bounds`), so this is a bootstrap-only lane,
    # the same shape and the same reason as the receptionist's mutation lane. See
    # this template's README.
    #
    # `reply_to` is not set here either, and also cannot be: the substrate stamps
    # every cell emission with the emitting cell's own path, so the colony's answer
    # comes back to this cell without anybody asking for it.
    return [{"header": {"route": "ask_colony"}, "messages": [], "query": {"scope": "/"}}]


if __name__ == "__main__":
    out = main()
    # A single emission is written as an object, several as an array — and an empty
    # list stays an empty array, which is how a `code` cell says "nothing to send"
    # (`parse_stdout_json`: a top-level array of length 0 is zero emissions). The
    # earlier `out[0]` shorthand would have raised IndexError on that case, which is
    # the pass this cell most needs to survive.
    sys.stdout.write(json.dumps(out[0] if len(out) == 1 else out))
